### ISSUE TITLE
Opencascade wrapper

### ISSUE THREAD

**Issue by cesarecaoduro** [devel0/SearchAThing.Solid#1]
Ciao, ho trovato per caso la libreria mentre cercavo informazioni su wrapper per opencascade.
Mi farebbe piacere fare due chiacchiere per capire se hai intenzione di svilupparlo ancora e per avere qualche dritta.
Grazie

**Comment by devel0** [comment]
Of course, you can contact me ( see email at https://github.com/devel0?tab=repositories ) so we can talk about it.
